{
 "title": "Microserviços Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=\"projeto-final-sd_orders_1\"}"
    }
   ]
  },
  {
   "title": "Latência",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(metricas_request_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notificações",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(notifications_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pagamentos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(payments_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(orders_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(orders_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests (metricas)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(metricas_requests_total[5m]))"
    }
   ]
  }
 ]
}